### PR TITLE
updated to work with jpm ( xpi filename is uglay )

### PR DESCRIPTION
**Pull request by canuckistani**
I wanted to build using jpm. The unresolved issue is that jpm uses the package.json id field to name the xpi file - this is pretty ugly because copy shorturl uses an old generated id from cfx days.

¯\_(ツ)_/¯

### CODE REVIEW

**Comment by fwenzel** [comment]
So long as this doesn't mess with my add-on ID (because AMO cares), this seems reasonable.

I haven't used jpm ever, should I?

**Comment by fwenzel** [comment]
Okay I'll transition to jpm, there doesn't seem to be a reason not to. Thanks!

**Comment by canuckistani** [comment]
@fwenzel jpm is supported as of Firefox 37, and cfx is deprecated and will not be updated. There are two really cool things about jpm ( amongst a big list of other awesome things ):

1. `jpm watchpost` works with the '[extension autoinstaller](https://addons.mozilla.org/en-us/firefox/addon/autoinstaller/)' extension to automatically update the extension in Firefox every time you save.
2. jpm supports loading compatible modules from ./node_modules, so you can install dependencies using npm.

**Comment by fwenzel** [comment]
Thanks for the info! I also filed this https://bugzilla.mozilla.org/show_bug.cgi?id=1153954 because the filename issue is silly.

**Pull request merged**
