### PR TITLE
complete L10n & Add zh_CN locale

### LINKED ISSUE #61: Name translators in manifest file
https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json

### PR DESCRIPTION
**Pull request by yfdyh000**
This also fix #61.

### CODE REVIEW

**Comment by fwenzel** [comment]
This is awesome, thanks a ton!

**Comment by fwenzel** [comment]
Question, how does this fix #61? Did you forget to commit a file?

**Comment by fwenzel** [comment]
I released version 4.3 with your code in it. Thank you!

**Comment by yfdyh000** [comment]
> Question, how does this fix #61? Did you forget to commit a file?

This fixes the purpose of #61 in WebExtension, i.e. name localizable.

**Comment by fwenzel** [comment]
Ah that was not the purpose of #61 but this change was great anyway. Thank you!

**Comment by yfdyh000** [comment]
Oops, I am mistaken the "translators" to "translations"...

**Pull request merged**
